"""empty message

Revision ID: b29ef0daab0e
Revises: 261fc172bf74
Create Date: 2023-05-11 17:23:48.241275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29ef0daab0e'
down_revision = '261fc172bf74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
